#!/usr/bin/env node
/**
 * Builds src/i18n/zh.generated.ts from the extracted strings.
 *
 * tools/i18n-strings.json holds { "<English source>": "<Chinese>" }. An entry
 * with an empty value is simply not emitted, and the runtime falls back to the
 * English source (see src/i18n/index.ts).
 *
 * Usage:
 *   node tools/i18n-build.mjs            write zh.generated.ts + report
 *   node tools/i18n-build.mjs --missing  list untranslated keys only
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STRINGS_PATH = path.join(ROOT, "tools", "i18n-strings.json");
const OUT_PATH = path.join(ROOT, "src", "i18n", "zh.generated.ts");
const MISSING_ONLY = process.argv.includes("--missing");

if (!fs.existsSync(STRINGS_PATH)) {
  console.error(`missing ${path.relative(ROOT, STRINGS_PATH)} — run tools/i18n-extract.mjs first`);
  process.exit(1);
}

const strings = JSON.parse(fs.readFileSync(STRINGS_PATH, "utf8"));
const entries = Object.entries(strings);
const translated = entries.filter(([, zh]) => typeof zh === "string" && zh.trim());
const missing = entries.filter(([, zh]) => !(typeof zh === "string" && zh.trim())).map(([en]) => en);

if (MISSING_ONLY) {
  for (const key of missing) console.log(key);
  console.log(`\n${missing.length} of ${entries.length} keys untranslated`);
  process.exit(0);
}

const lines = [
  "/**",
  " * Generated by tools/i18n-build.mjs — do not edit by hand.",
  " * Source: tools/i18n-strings.json (run tools/i18n-extract.mjs to collect keys).",
  " * Strings with no entry here fall back to English at runtime.",
  " */",
  "export const zhGenerated: Record<string, string> = {",
];
for (const [en, zh] of translated) {
  lines.push(`  ${JSON.stringify(en)}: ${JSON.stringify(zh)},`);
}
lines.push("};", "");

fs.writeFileSync(OUT_PATH, lines.join("\n"));
console.log(
  `wrote ${path.relative(ROOT, OUT_PATH)}: ${translated.length} translated, ${missing.length} still English`
);
